SUMMARY = "package group for all rubygems"

inherit packagegroup

RDEPENDS_${PN} += "\
    rubygems-addressable \
    rubygems-bcrypt-pbkdf \
    rubygems-builder \
    rubygems-bundler \
    rubygems-chef \
    rubygems-chef-config \
    rubygems-chef-utils \
    rubygems-chef-zero \
    rubygems-coderay \
    rubygems-concurrent-ruby \
    rubygems-deep-merge \
    rubygems-diff-lcs \
    rubygems-ed25519 \
    rubygems-erubi \
    rubygems-erubis \
    rubygems-facter \
    rubygems-fast-gettext \
    rubygems-ffi \
    rubygems-ffi-libarchive \
    rubygems-ffi-yajl \
    rubygems-fuzzyurl \
    rubygems-gssapi \
    rubygems-gyoku \
    rubygems-hashie \
    rubygems-hiera \
    rubygems-highline \
    rubygems-hocon \
    rubygems-httpclient \
    rubygems-iniparse \
    rubygems-ipaddress \
    rubygems-libyajl2 \
    rubygems-license-acceptance \
    rubygems-little-plugger \
    rubygems-locale \
    rubygems-logging \
    rubygems-method-source \
    rubygems-mixlib-archive \
    rubygems-mixlib-authentication \
    rubygems-mixlib-cli \
    rubygems-mixlib-config \
    rubygems-mixlib-log \
    rubygems-mixlib-shellout \
    rubygems-multi-json \
    rubygems-net-scp \
    rubygems-net-sftp \
    rubygems-net-ssh \
    rubygems-net-ssh-gateway \
    rubygems-net-ssh-multi \
    rubygems-nori \
    rubygems-ohai \
    rubygems-pastel \
    rubygems-plist \
    rubygems-proxifier \
    rubygems-pry \
    rubygems-public-suffix \
    rubygems-puppet \
    rubygems-puppet-resource-api \
    rubygems-rack \
    rubygems-rubyntlm \
    rubygems-rubyzip \
    rubygems-semantic-puppet \
    rubygems-strings \
    rubygems-strings-ansi \
    rubygems-syslog-logger \
    rubygems-systemu \
    rubygems-thor \
    rubygems-tomlrb \
    rubygems-train-core \
    rubygems-train-winrm \
    rubygems-tty-box \
    rubygems-tty-color \
    rubygems-tty-cursor \
    rubygems-tty-prompt \
    rubygems-tty-reader \
    rubygems-tty-screen \
    rubygems-unicode-display-width \
    rubygems-unicode-utils \
    rubygems-uuidtools \
    rubygems-winrm \
    rubygems-winrm-elevated \
    rubygems-winrm-fs \
    rubygems-wisper \
    rubygems-wmi-lite \
    rubygems-yajl-ruby \
"
