name: "[cron]-cherry-pick-from-upstream-master"

on: pull_request

jobs:
  buildrun:
    name: "build"
    env:
      BUILD_EXPORT: 1
      SCM_BRANCH: test/cherry-pick
      BUILD_GLIBC: 1
      BUILD_KERNEL: 1
      BUILD_MAXRUNTIME: 21000
      BUILD_QEMUSYSTEM: 1
      PYTHONIOENCODING: utf8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8

    runs-on: ubuntu-latest

    container:
      image: privkweihmann/yocto-sca-minimal:latest
      env:
        WORKSPACE: /opt/build
        TOPDIR: /opt/build
        TEMPLATECONF: /opt/build/sources/meta-rubygems/conf/variant/rubygems-x86-64-glibc
      volumes:
        - ${{ github.workspace }}:/opt/build
      options: --privileged --user=yoctouser

    steps:
      - name: setup (container)
        uses: priv-kweihmann/meta-sca-ci-utils/preparecontainer@latest
      - name: setup (caches)
        run: |
          mkdir -p ${WORKSPACE}/sstate-cache
        shell: bash
      - name: checkout (poky)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: git://git.yoctoproject.org/poky.git
          ref: 2b49a8fbf0c7965982e50e6e2643b17523c119c9
          remove-git: "0"
          add-layer: "0"
      - name: checkout (meta-rubygems)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: https://github.com/${{ github.repository }}.git
          branch: ${{ env.SCM_BRANCH }}
          remove-git: "0"
          add-layer: "0"
      - name: checkout (meta-openembedded)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: git://git.openembedded.org/meta-openembedded
          ref: 9cf4ebeb3de524009a73f49722489dc4aa183adb
          branch: none
          remove-git: "0"
          add-layer: "0"
      - name: set upstream info
        run: |
          sudo chmod -R 0777 /__w/ 
          cd ${WORKSPACE}/sources/meta-rubygems
          git remote add upstream https://github.com/priv-kweihmann/meta-rubygems.git
          git remote add downstream https://github.com/${{ github.repository }}.git
          git fetch upstream
          git fetch downstream
      - name: build (revision update)
        run: |
          GIT_USER="${{ secrets.BOTNAME }}" \
          GIT_MAIL="${{ secrets.BOTMAIL }}" \
          GIT_USERNAME="${{ secrets.BOTGITUSER }}" \
          GIT_PASSWORD="${{ secrets.BOTTOKEN }}" \
          GITHUB_REPO_USER=${{ github.repository_owner }} \
          GITHUB_REPO=meta-rubygems \
          ${WORKSPACE}/sources/meta-rubygems/scripts/cherry-pick-bot \
          --cpmode=firstcommon \
          upstream/master \
          downstream/${{ env.SCM_BRANCH }} \
          ${WORKSPACE}/sources/meta-rubygems/.nocherry
        shell: bash
        env:
          PYTHONUNBUFFERED: 1
