name: "[cron]-[glibc]-[qemuarm64]-[cherrypick]-[dunfell]"

on:
  repository_dispatch:
    types: do-dunfell-cherry-pick
  schedule:
    - cron: "0 2 * * 1"

jobs:
  buildrun:
    name: "build"
    env:
      BUILD_EXPORT: 1
      SCM_BRANCH: master
      BUILD_GLIBC: 1
      BUILD_KERNEL: 1
      BUILD_MAXRUNTIME: 21000
      BUILD_QEMUSYSTEM: 1
      PYTHONIOENCODING: utf8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8

    runs-on: ubuntu-latest

    container:
      image: privkweihmann/yocto-sca-minimal:latest
      env:
        WORKSPACE: /opt/build
        TOPDIR: /opt/build
        TEMPLATECONF: /opt/build/sources/meta-rubygems/conf/variant/rubygems-arm64-glibc
      volumes:
        - ${{ github.workspace }}:/opt/build
      options: --privileged

    steps:
      - name: setup (container)
        uses: priv-kweihmann/meta-sca-ci-utils/preparecontainer@latest
      - name: setup (caches)
        run: |
          mkdir -p ${WORKSPACE}/sstate-cache
        shell: bash
      - name: checkout (poky)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: git://git.yoctoproject.org/poky.git
          ref: 2c8f3be3a559158b1d475da1931a659dad5b9414
          branch: none
          remove-git: "0"
          add-layer: "0"
      - name: checkout (meta-rubygems)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: https://github.com/priv-kweihmann/meta-rubygems.git
          branch: ${{ env.SCM_BRANCH }}
          remove-git: "0"
          add-layer: "0"
      - name: checkout (meta-openembedded)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: git://git.openembedded.org/meta-openembedded
          ref: 268e844999c417010baecdf5b42c7b32e2f4b658
          branch: none
          remove-git: "0"
          add-layer: "0"
      - name: build (revision update)
        run: |
          GIT_USER="${{ secrets.BOTNAME }}" \
          GIT_MAIL="${{ secrets.BOTMAIL }}" \
          GIT_USERNAME="${{ secrets.BOTGITUSER }}" \
          GIT_PASSWORD="${{ secrets.BOTTOKEN }}" \
          GITHUB_REPO_USER=priv-kweihmann \
          GITHUB_REPO=meta-rubygems \
          ${WORKSPACE}/sources/meta-rubygems/scripts/cherry-pick-bot \
          --cpmode=firstcommon \
          origin/master \
          origin/dunfell \
          ${WORKSPACE}/sources/meta-rubygems/.nocherry
        shell: bash

