name: "[master]-[musl]-[qemux86-64]"

on:
  schedule: push

jobs:
  buildrun:
    name: "build"
    env:
      BUILD_EXPORT: 1
      SCM_BRANCH: master
      BUILD_GLIBC: 1
      BUILD_KERNEL: 1
      BUILD_MAXRUNTIME: 21000
      BUILD_QEMUSYSTEM: 1
      PYTHONIOENCODING: utf8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8

    runs-on: ubuntu-latest

    container:
      image: privkweihmann/yocto-sca-minimal:latest
      env:
        WORKSPACE: /opt/build
        TOPDIR: /opt/build
        TEMPLATECONF: /opt/build/sources/meta-rubygems/conf/variant/rubygems-x86-64-musl
      volumes:
        - ${{ github.workspace }}:/opt/build
      options: --privileged

    steps:
      - name: setup (container)
        uses: priv-kweihmann/meta-sca-ci-utils/preparecontainer@latest
      - name: checkout (poky)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: git://git.yoctoproject.org/poky.git
          branch: ${{ env.SCM_BRANCH }}
          add-layer: "0"
      - name: checkout (meta-rubygems)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: https://github.com/priv-kweihmann/meta-rubygems.git
          branch: ${{ env.SCM_BRANCH }}
      - if: env.BUILD_GLIBC == '1'
        name: build (glibc)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: glibc
      - if: env.BUILD_KERNEL == '1'
        name: build (kernel)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: linux-yocto
      - if: env.BUILD_QEMUSYSTEM == '1'
        name: build (qemu-system)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: qemu-system-native
      - name: build (core-image-minimal-rubygems)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: core-image-minimal-rubygems
      - name: test (core-image-minimal-rubygems)
        uses: priv-kweihmann/meta-sca-ci-utils/testimage@latest
        with:
          target: core-image-minimal-rubygems
