name: "[pr]-[musl]-[qemux86-64]"

on: pull_request

jobs:
  buildrun:
    name: "build"
    env:
      BUILD_EXPORT: 1
      SCM_BRANCH: master
      BUILD_GLIBC: 1
      BUILD_KERNEL: 1
      BUILD_MAXRUNTIME: 21000
      BUILD_QEMUSYSTEM: 1
      PYTHONIOENCODING: utf8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8

    runs-on: ubuntu-latest

    container:
      image: privkweihmann/yocto-sca-minimal:latest
      env:
        WORKSPACE: /opt/build
        TOPDIR: /opt/build
        TEMPLATECONF: /opt/build/sources/meta-rubygems/conf/variant/rubygems-x86-64-musl
      volumes:
        - ${{ github.workspace }}:/opt/build
      options: --privileged

    steps:
      - name: setup (container)
        uses: priv-kweihmann/meta-sca-ci-utils/preparecontainer@latest
      - name: checkout (poky)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: git://git.yoctoproject.org/poky.git
          ref: 7a348cdc3ad084a1799b0939c3192691049ba08e
          branch: none
          add-layer: "0"
      - name: checkout (meta-rubygems)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: auto-determine
          branch: auto-determine
          gh-event-file: "1"
          add-layer: "0"
          remove-git: "0"
      - name: checkout (meta-openembedded)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: git://git.openembedded.org/meta-openembedded
          ref: 390c4d638e9fb6df858813a0e681e573f921ae83
          branch: none
          add-layer: "0"
      - name: setup (caches)
        run: |
          sudo mkdir -p /__w/_temp/_runner_file_commands
          sudo chmod -R 0777 /__w/_temp/_runner_file_commands
          sudo echo "rubygems_master_rev=$(git -C /opt/build/sources/meta-rubygems/ rev-parse origin/master)" >> $GITHUB_ENV
          mkdir -p ${WORKSPACE}/sstate-cache
      - name: configure (caches)
        uses: actions/cache@v2
        with:
          path: /opt/build/sstate-cache
          key: rubygems-x86-64-musl-${{ env.rubygems_master_rev }}
      - name: activate (caches)
        uses: priv-kweihmann/meta-sca-ci-utils/addvar@latest
        with:
          variable: SSTATE_MIRRORS
          value: "file://.* file:///${WORKSPACE}/sstate-cache/PATH"
      - if: env.BUILD_GLIBC == '1'
        name: build (glibc)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: glibc
      - if: env.BUILD_KERNEL == '1'
        name: build (kernel)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: linux-yocto
      - if: env.BUILD_QEMUSYSTEM == '1'
        name: build (qemu-system)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: qemu-system-native
      - name: setup (rm_work_and_downloads)
        uses: priv-kweihmann/meta-sca-ci-utils/addvar@latest
        with:
          variable: INHERIT
          operation: " += "
          value: "rm_work_and_downloads rubygemsdebug"
      - name: build (core-image-minimal-rubygems)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: core-image-minimal-rubygems
      - name: test (core-image-minimal-rubygems)
        uses: priv-kweihmann/meta-sca-ci-utils/testimage@latest
        with:
          target: core-image-minimal-rubygems
          tapgen: "0"
