name: "[pull-request-bot-oelint]"

on: pull_request

jobs:
  check:
    name: "build"
    runs-on: ubuntu-22.04

    container:
      image: privkweihmann/yocto-sca-minimal:2004
      volumes:
        - ${{ github.workspace }}:/opt/build
      options: --privileged --user=yoctouser

    steps:
      - name: setup (container)
        uses: priv-kweihmann/meta-sca-ci-utils/preparecontainer@latest
      - name: setup (workspace)
        run: |
          sudo chmod -R 0777 "/__w/"
        shell: bash
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: prcode
      - name: check (oelint)
        uses: priv-kweihmann/meta-sca-ci-utils/oelint@latest
        with:
          sources: /__w/meta-rubygems/meta-rubygems/prcode
          custom-rule-dir: /__w/meta-rubygems/meta-rubygems/prcode/files/lint/oelint-custom
          config-file: /__w/meta-rubygems/meta-rubygems/prcode/files/lint/oelint-rulefile.json
          constant-file: /__w/meta-rubygems/meta-rubygems/prcode/files/lint/oelint-constants.json
          username: priv-kweihmann
          token: ${{ secrets.BOTTOKEN }}
          pull-request-repo-user: priv-kweihmann
          pull-request-repo: meta-rubygems
      