name: "[pull-request-bot]"

on: pull_request

jobs:
  check:
    name: "build"
    runs-on: ubuntu-latest

    container:
      image: privkweihmann/yocto-sca-minimal:latest
      volumes:
        - ${{ github.workspace }}:/opt/build
      options: --privileged

    steps:
      - name: setup (container)
        uses: priv-kweihmann/meta-sca-ci-utils/preparecontainer@latest
      - name: setup (workspace)
        run: |
          sudo chown "/__w/"
        shell: bash
      - name: checkout
        uses: actions/checkout@v2
      - name: check (oelint)
        uses: priv-kweihmann/meta-sca-ci-utils/oelint@latest
        with:
          sources: ${{ github.workspace }}
          custom-rule-dir: ${{ github.workspace }}/.github/oelint-custom
          config-file: ${{ github.workspace }}/.github/oelint-rulefile.json
          constant-file: ${{ github.workspace }}/.github/oelint-constants.json
          username: priv-kweihmann
          token: ${{ secrets.BOTTOKEN }}
          pull-request-repo-user: priv-kweihmann
          pull-request-repo: meta-rubygems
      