name: "[master]-[musl]-[qemux86-64]"

on:
  push:
    branches:
      - master

jobs:
  buildrun:
    name: "build"
    env:
      BUILD_EXPORT: 1
      SCM_BRANCH: master
      BUILD_GLIBC: 1
      BUILD_KERNEL: 1
      BUILD_MAXRUNTIME: 21000
      BUILD_QEMUSYSTEM: 1
      PYTHONIOENCODING: utf8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LANGUAGE: en_US.UTF-8

    runs-on: ubuntu-latest

    container:
      image: privkweihmann/yocto-sca-minimal:latest
      env:
        WORKSPACE: /opt/build
        TOPDIR: /opt/build
        TEMPLATECONF: /opt/build/sources/meta-rubygems/conf/variant/rubygems-x86-64-musl
      volumes:
        - ${{ github.workspace }}:/opt/build
      options: --privileged

    steps:
      - name: setup (container)
        uses: priv-kweihmann/meta-sca-ci-utils/preparecontainer@latest
      - name: setup (caches)
        run: |
          mkdir -p ${WORKSPACE}/sstate-cache
        shell: bash
      - name: additional setup (caches)
        uses: actions/cache@v2
        with:
          path: /opt/build/sstate-cache
          key: rubygems-x86-64-musl-${{ github.sha }}
      - name: checkout (poky)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: git://git.yoctoproject.org/poky.git
          ref: ed7151f9856791fc4a24b1a0a88f87c442b29f38
          branch: none
          add-layer: "0"
      - name: checkout (meta-rubygems)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: https://github.com/priv-kweihmann/meta-rubygems.git
          branch: ${{ env.SCM_BRANCH }}
          add-layer: "0"
      - name: checkout (meta-openembedded)
        uses: priv-kweihmann/meta-sca-ci-utils/addlayer@latest
        with:
          repo: git://git.openembedded.org/meta-openembedded
          ref: bb743fc71d3b0bc22b6c4a6ada44b63c38914dc4
          branch: none
          add-layer: "0"
      - name: configure (caches)
        uses: priv-kweihmann/meta-sca-ci-utils/addvar@latest
        with:
          variable: SSTATE_DIR
          value: /opt/build/sstate-cache
      - if: env.BUILD_GLIBC == '1'
        name: build (glibc)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: glibc
      - if: env.BUILD_KERNEL == '1'
        name: build (kernel)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: linux-yocto
      - if: env.BUILD_QEMUSYSTEM == '1'
        name: build (qemu-system)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: qemu-system-native
      - name: setup (rm_work_and_downloads)
        uses: priv-kweihmann/meta-sca-ci-utils/addvar@latest
        with:
          variable: INHERIT
          operation: " += "
          value: "rm_work_and_downloads rubygemsdebug"
      - name: build (core-image-minimal-rubygems)
        uses: priv-kweihmann/meta-sca-ci-utils/buildstep@latest
        with:
          target: core-image-minimal-rubygems
